var rule = {
    title: '笔趣阁漫画',
    host: 'https://www.biqumh.com',
    url: '/fyclass/fypage.html',
    searchUrl: '/search/wd/**/page/fypage.html',
    searchable: 2,
    quickSearch: 0,
    headers: {
        'User-Agent': 'MOBILE_UA',
    },
    timeout: 5000,
    class_name: '连载&完结&日漫&国漫',
    class_url: 'lianzai&wanjie&riman&guoman',
    play_parse: true,
    lazy: '',
    limit: 6,
    推荐: '.list;a&&title;img&&src;.desc&&Text;a&&href',
    double: true,
    一级: '.list;a&&title;img&&src;.desc&&Text;a&&href',
    二级: '*',
    搜索: '.list;a&&title;img&&src;.desc&&Text;a&&href',
}
